### ISSUE TITLE
More customization using settings

### ISSUE THREAD

**Issue by fedemotta** [mcuznz/jquery.dayparts#2]
Hi,
I am using this jquery library (which is exactly what I was looking for! Thank you!). I need to  add some customization to full fill my requirements. I added a couple of settings in PR #1 .
- change0Hour (Default as true):
  You are able to keep the 0 hour as 0 (by default it changes to 24 or 12 based in use24HFormat).
- show2DigitsHour (Default as false):
  It shows all hours in 00 format.
- disabled (Default as false):
  Use dayparts as read only.
- presetsSubtitle (Default as ''):
  It shows some text before the presets.

Feel free to merge or close the PR. Just a contribution to your work.

Thanks

**Comment by mcuznz** [comment]
I totally missed the notification for this PR, sorry!  Thanks for contributing, I've merged this in :D

**Comment by fedemotta** [comment]
Thank you!
